# src/reporting.py
import datetime


def generate_sample_report_markdown(project_name: str, audit_data: dict) -> str:
    """Formats audit results into a structured, executive-ready Markdown report."""
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
    res = audit_data.get("result", audit_data)
    status = res.get("status", "OK")
    risks = res.get("risks", [])

    high_risks = sum(
        1 for r in risks if r.get("is_sev1", False) or r.get("is_contradiction", False)
    )
    medium_risks = len(risks) - high_risks
    risk_score = max(0, 100 - (high_risks * 15) - (medium_risks * 5))

    health = "Red" if high_risks > 0 else ("Amber" if medium_risks > 0 else "Green")

    md = f"""# Delivery Risk Assessment Report: Project {project_name.upper()}
**Generated by Delivery Risk Assistant**  
**Analysis Timestamp:** {timestamp}  
**Status:** {status}  

---

## 📈 Executive Summary Dashboard
- **Overall Delivery Health:** {health}
- **Risk Score:** {risk_score}/100
- **High Risks (SEV-1/Blockers):** {high_risks}
- **Medium/Low Risks:** {medium_risks}

---

## 🛡️ Detailed Risk Breakdown ({len(risks)})
"""

    if not risks:
        md += "\nNo critical delivery risks detected in the active knowledge base.\n"
    else:
        for idx, r in enumerate(risks, 1):
            impact = r.get("impact_breakdown", {})
            md += f"""### {idx}. {r.get("risk", "Unnamed Risk")}
- **Evidence Confidence:** {r.get("evidence_confidence", 85)}%
- **Data Tag:** `{r.get("confidence_tag", "directional_estimate")}`
- **Explanation:** {r.get("explanation", "No explanation provided.")}

**Business Impact:**
- **Delivery:** {impact.get("delivery_impact", "N/A")}
- **Customer:** {impact.get("customer_impact", "N/A")}
- **Business/Revenue:** {impact.get("business_impact", "N/A")}
- **Team:** {impact.get("team_impact", "N/A")}

**Actionable Recommendations:**
"""
            for rec in r.get("recommendations", []):
                md += f"- {rec}\n"

            cits = r.get("citations", [])
            if cits:
                md += f"\n**Grounded Citations:** `{', '.join(cits)}`\n"
            md += "\n---\n"

    return md
